In [76]:
# Import necessary libraries
import pandas as pd
import geopandas as gpd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Data Cleaning

In [77]:
# Loading the population data
population = pd.read_csv(".\data\county_year_population.csv")

# Displaying the first few rows 
population.tail(10)

#print(population['county'])

,county,year,population,land_area_km2,density_km2,growth_pct_per_yr
1212,West Pokot,2016,586460,9123,64.3,1.92
1213,West Pokot,2017,597832,9123,65.5,1.92
1214,West Pokot,2018,609424,9123,66.8,1.92
1215,West Pokot,2019,621241,9123,68.1,1.92
1216,West Pokot,2020,633287,9123,69.4,1.92
1217,West Pokot,2021,645567,9123,70.8,1.92
1218,West Pokot,2022,658085,9123,72.1,1.92
1219,West Pokot,2023,670845,9123,73.5,1.92
1220,West Pokot,2024,683853,9123,75.0,1.92
1221,West Pokot,2025,697113,9123,76.4,1.92

In [78]:
# Loading kenya_crosswalk
crosswalk = pd.read_csv(".\data\data\kenya_county_crosswalk.csv")

# first few
crosswalk['county']

0             Mombasa
1               Kwale
2              Kilifi
3          Tana River
4                Lamu
5        Taita-Taveta
6             Garissa
7               Wajir
8             Mandera
9            Marsabit
10             Isiolo
11               Meru
12      Tharaka-Nithi
13               Embu
14              Kitui
15           Machakos
16            Makueni
17          Nyandarua
18              Nyeri
19          Kirinyaga
20           Murang'a
21             Kiambu
22            Turkana
23         West Pokot
24            Samburu
25        Trans Nzoia
26        Uasin Gishu
27    Elgeyo-Marakwet
28              Nandi
29            Baringo
30           Laikipia
31             Nakuru
32              Narok
33            Kajiado
34            Kericho
35              Bomet
36           Kakamega
37             Vihiga
38            Bungoma
39              Busia
40              Siaya
41             Kisumu
42           Homa Bay
43             Migori
44              Kisii
45            Nyamira
46            Nairobi
Name: county, dtype: str

In [79]:
# Loading land cover county
landcover = pd.read_csv(".\data\data\worldcover_landcover_county.csv")

# Isolating the percentages
calculate = landcover[['pct_bare', 'pct_bare', 'pct_crop', 'pct_grass', 'pct_mangrove', 'pct_shrub', 'pct_tree', 'pct_water', 'pct_wetland']]
landcover['total'] = calculate.select_dtypes(include="number").sum(axis=1).round(1)

# Removing total != 1.0
#landcover = landcover[landcover['total'] >= 1.0]
#landcover.head(48)

In [80]:
landcover.info()

<class 'pandas.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   system:index  47 non-null     str
 1   COUNT         47 non-null     int64
 2   COUNTYCO      47 non-null     int64
 3   FIRST_COUN    47 non-null     str
 4   area_km2      47 non-null     float64
 5   pct_bare      47 non-null     float64
 6   pct_built     47 non-null     float64
 7   pct_crop      47 non-null     float64
 8   pct_grass     47 non-null     float64
 9   pct_mangrove  47 non-null     float64
 10  pct_shrub     47 non-null     float64
 11  pct_tree      47 non-null     float64
 12  pct_water     47 non-null     float64
 13  pct_wetland   47 non-null     float64
 14  .geo          47 non-null     str
 15  total         47 non-null     float64
dtypes: float64(11), int64(2), str(3)
memory usage: 6.0 KB

In [81]:
landcover.columns

Index(['system:index', 'COUNT', 'COUNTYCO', 'FIRST_COUN', 'area_km2',
       'pct_bare', 'pct_built', 'pct_crop', 'pct_grass', 'pct_mangrove',
       'pct_shrub', 'pct_tree', 'pct_water', 'pct_wetland', '.geo', 'total'],
      dtype='str')

In [82]:
# Loading kenya_county geo area
geography = gpd.read_file(".\data\data\kenya_counties.geojson")

In [83]:
population.info(), crosswalk.info(), landcover.info()

<class 'pandas.DataFrame'>
RangeIndex: 1222 entries, 0 to 1221
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   county             1222 non-null   str
 1   year               1222 non-null   int64
 2   population         1222 non-null   int64
 3   land_area_km2      1222 non-null   int64
 4   density_km2        1222 non-null   float64
 5   growth_pct_per_yr  1222 non-null   float64
dtypes: float64(2), int64(3), str(1)
memory usage: 57.4 KB
<class 'pandas.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   county            47 non-null     str
 1   knbs_code         47 non-null     int64
 2   pcode             47 non-null     str
 3   desinventar_code  47 non-null     int64
 4   desinventar_name  47 non-null     str
dtypes: int64(2), str(3)
memory usage: 2.0 KB
<class 'pandas.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   system:index  47 non-null     str
 1   COUNT         47 non-null     int64
 2   COUNTYCO      47 non-null     int64
 3   FIRST_COUN    47 non-null     str
 4   area_km2      47 non-null     float64
 5   pct_bare      47 non-null     float64
 6   pct_built     47 non-null     float64
 7   pct_crop      47 non-null     float64
 8   pct_grass     47 non-null     float64
 9   pct_mangrove  47 non-null     float64
 10  pct_shrub     47 non-null     float64
 11  pct_tree      47 non-null     float64
 12  pct_water     47 non-null     float64
 13  pct_wetland   47 non-null     float64
 14  .geo          47 non-null     str
 15  total         47 non-null     float64
dtypes: float64(11), int64(2), str(3)
memory usage: 6.0 KB

(None, None, None)

In [ ]:
# Data cleaning function
def population_cleaning(data, data2, data3):
    # 1. Keeping the years from 2019
    data = data[data['year']==2019]

    # 2. Add log_density
    data['log_density'] = np.log(data['density_km2'])

    # 3. Adding county codes from crosswalk
    #data["county_codes"] = data["county"].map(data2["pcode"])
    county_to_code = data2.set_index("county")["knbs_code"]
    data["county_codes"] = data["county"].map(county_to_code)

    # 3.2 correcting the spelling of Taita Taveta
    data["county"] = data["county"].replace({"Taita Taveta": "Taita-Taveta"})
    data["county_codes"] = data["county"].map(county_to_code)

    # 3.3 Adding desinventar_code to the data
    crosswalk_by_county = data2.set_index("county")
    data["desinventar_code"] = data["county"].map(crosswalk_by_county["desinventar_code"])
    
    # 4. Reordering the positions of the columns
    data = data[['county_codes', 'county', 'desinventar_code', 'year', 'population', 'land_area_km2', 'density_km2', 'log_density', 'growth_pct_per_yr']]

    # 5.1 Joining the landcover data into the main data
    # 5.2 Creating a list of the columns to add
    country_to_landcover = ['COUNTYCO','pct_bare', 'pct_bare', 'pct_crop', 'pct_grass', 'pct_mangrove', 'pct_shrub', 'pct_tree', 'pct_water', 'pct_wetland']
    data = pd.merge(
        data,
        data3[country_to_landcover],
        left_on="county_codes",  # The column name in data
        right_on="COUNTYCO",  # The column name in data3
        how="left",
    )
    data = data.drop("COUNTYCO", axis=1)

    # Return the data
    return data

In [87]:
# Calling the function
df = population_cleaning(population, crosswalk, landcover)
df = df.sort_values(by='county_codes').reset_index(drop=True)
df.head(47)

,county_codes,county,desinventar_code,year,population,land_area_km2,density_km2,log_density,growth_pct_per_yr,pct_bare,pct_bare,pct_crop,pct_grass,pct_mangrove,pct_shrub,pct_tree,pct_water,pct_wetland
0,1,Mombasa,28,2019,1208333,220,5492.4,8.611121,2.52,0.002472,0.002472,0.048634,0.130316,0.000000,0.500581,0.290396,0.025629,4.860347e-04
1,2,Kwale,19,2019,866820,8267,104.9,4.653008,2.88,0.000138,0.000138,0.023655,0.329924,0.000000,0.291430,0.351073,0.000111,1.175836e-04
2,3,Kilifi,14,2019,1453787,12540,115.9,4.752728,2.70,0.000174,0.000174,0.363496,0.124589,0.000000,0.211135,0.290265,0.000087,1.140689e-04
3,4,Tana River,40,2019,315943,37951,8.3,2.116256,2.75,0.000402,0.000402,0.198725,0.198304,0.000000,0.409546,0.148480,0.006333,2.783485e-02
4,5,Lamu,21,2019,143920,6253,23.0,3.135494,3.49,0.001977,0.001977,0.149025,0.098885,0.000000,0.471857,0.259881,0.012694,7.423277e-04
5,6,Taita-Taveta,39,2019,340671,17152,19.9,2.990720,1.80,0.002210,0.002210,0.001662,0.179479,0.000000,0.739879,0.075553,0.000399,6.897950e-05
6,7,Garissa,6,2019,841353,44736,18.8,2.933857,3.00,0.000571,0.000571,0.126129,0.290137,0.000000,0.422557,0.132632,0.021108,9.252711e-04
7,8,Wajir,46,2019,781263,56773,13.8,2.624669,1.66,0.020103,0.020103,0.000977,0.550222,0.000000,0.418645,0.009366,0.000093,1.975856e-04
8,9,Mandera,24,2019,867457,25940,33.4,3.508556,-1.68,0.013467,0.013467,0.032401,0.482047,0.000000,0.440438,0.025680,0.002116,5.671588e-04
9,10,Marsabit,25,2019,459785,70944,6.5,1.871802,4.57,0.000551,0.000551,0.315609,0.081227,0.000000,0.212227,0.380300,0.000574,2.213970e-04
10,11,Isiolo,8,2019,268002,25350,10.6,2.360854,6.26,0.000892,0.000892,0.092622,0.113232,0.000000,0.229263,0.561140,0.000411,1.882944e-04
11,12,Meru,26,2019,1545714,7006,220.6,5.396351,1.31,0.000219,0.000219,0.087316,0.101096,0.000000,0.235198,0.571583,0.000166,1.264510e-04
12,13,Tharaka-Nithi,41,2019,393177,2564,153.3,5.032397,0.73,0.002849,0.002849,0.138140,0.154078,0.000000,0.249758,0.395751,0.004194,2.191933e-04
13,14,Embu,5,2019,608599,2821,215.7,5.373889,1.65,0.001629,0.001629,0.014956,0.165631,0.001732,0.535550,0.272492,0.004452,1.234336e-03
14,15,Kitui,18,2019,1136187,30430,37.3,3.618993,1.15,0.004494,0.004494,0.324101,0.053318,0.000000,0.127910,0.456619,0.000229,2.037844e-02
15,16,Machakos,22,2019,1421932,6043,235.3,5.460861,2.58,0.000106,0.000106,0.035010,0.021100,0.000000,0.227099,0.693353,0.000038,1.516634e-05
16,17,Makueni,23,2019,987653,8170,120.9,4.794964,1.10,0.000609,0.000609,0.082633,0.447420,0.000000,0.207295,0.220599,0.007924,1.666918e-02
17,18,Nyandarua,35,2019,638289,3286,194.2,5.268889,0.68,0.002260,0.002260,0.093798,0.086608,0.000000,0.684574,0.131216,0.000951,0.000000e+00
18,19,Nyeri,36,2019,759164,3325,228.3,5.430661,0.90,0.001458,0.001458,0.027998,0.333824,0.004013,0.483706,0.143720,0.002130,4.973766e-04
19,20,Kirinyaga,15,2019,610411,1478,413.0,6.023448,1.45,0.000636,0.000636,0.090718,0.637806,0.000000,0.225977,0.040826,0.000859,9.479567e-05
20,21,Murang'a,29,2019,1056640,2524,418.6,6.036916,1.14,0.000903,0.000903,0.022979,0.271382,0.016400,0.181797,0.485897,0.016378,3.944625e-03
21,22,Kiambu,13,2019,2417735,2539,952.2,6.858775,3.98,0.003013,0.003013,0.200665,0.344958,0.000000,0.374958,0.048896,0.014739,1.307926e-04
22,23,Turkana,43,2019,926976,68233,13.6,2.610070,0.80,0.002540,0.002540,0.193341,0.178718,0.000000,0.490293,0.130558,0.002254,0.000000e+00
23,24,West Pokot,47,2019,621241,9123,68.1,4.220977,1.92,0.000234,0.000234,0.000048,0.040100,0.000000,0.958955,0.000380,0.000010,0.000000e+00
24,25,Samburu,37,2019,310327,21065,14.7,2.687847,3.26,0.157395,0.157395,0.000308,0.548322,0.000000,0.287005,0.006481,0.000384,6.702837e-05
25,26,Trans Nzoia,42,2019,990341,2495,396.9,5.983684,1.90,0.002535,0.002535,0.165730,0.281066,0.000000,0.262488,0.279090,0.000388,3.858949e-03
26,27,Uasin Gishu,44,2019,1163186,3392,342.9,5.837439,2.63,0.000698,0.000698,0.364297,0.209694,0.000000,0.249458,0.161247,0.003685,1.412253e-03
27,28,Elgeyo-Marakwet,11,2019,454480,3032,149.9,5.009968,2.06,0.026410,0.026410,0.007911,0.291651,0.052053,0.039992,0.220598,0.103933,1.910225e-02
28,29,Nandi,32,2019,885711,2856,310.1,5.736895,1.62,0.000338,0.000338,0.159833,0.040759,0.000000,0.355706,0.431896,0.001133,6.890698e-05
29,30,Baringo,1,2019,666763,10976,60.7,4.105944,1.82,0.009659,0.009659,0.043417,0.297044,0.000000,0.097027,0.208994,0.006369,7.163260e-05
30,31,Laikipia,20,2019,518580,9532,54.4,3.996364,2.62,0.002686,0.002686,0.283522,0.311051,0.000000,0.137855,0.225759,0.015399,2.299550e-04
31,32,Nakuru,31,2019,2162202,7462,289.8,5.669191,2.99,0.000017,0.000017,0.131837,0.124329,0.000000,0.277345,0.462912,0.000082,4.545843e-04
32,33,Narok,33,2019,1157873,17950,64.5,4.166665,3.08,0.001873,0.001873,0.110973,0.489076,0.000000,0.207005,0.189602,0.000136,1.019494e-04
33,34,Kajiado,9,2019,1117840,21871,51.1,3.933784,4.86,0.000055,0.000055,0.013773,0.034631,0.000000,0.274168,0.664185,0.000170,1.108252e-05
34,35,Kericho,12,2019,901777,2436,370.2,5.914043,1.73,0.000227,0.000227,0.259651,0.269431,0.000000,0.210603,0.240262,0.009993,2.408228e-03
35,36,Bomet,2,2019,875689,2531,346.0,5.846439,1.90,0.001340,0.001340,0.064321,0.205849,0.000000,0.292077,0.427505,0.000397,8.059752e-05
36,37,Kakamega,10,2019,1867579,3020,618.4,6.427135,1.17,0.012097,0.012097,0.003354,0.291811,0.000000,0.637897,0.054224,0.000294,3.786861e-05
37,38,Vihiga,45,2019,590013,564,1046.1,6.952824,0.62,0.001000,0.001000,0.120394,0.318438,0.000000,0.424555,0.103412,0.013052,1.429052e-02
38,39,Bungoma,3,2019,1670570,3024,552.4,6.314272,0.24,0.001172,0.001172,0.016918,0.466242,0.000000,0.475514,0.036203,0.000716,1.878181e-03
39,40,Busia,4,2019,893681,1696,526.9,6.267011,6.05,0.001648,0.001648,0.011630,0.160118,0.000811,0.788054,0.034471,0.001226,1.736461e-03
40,41,Siaya,38,2019,993183,2530,392.6,5.972791,1.65,0.003333,0.003333,0.156897,0.108760,0.000000,0.434655,0.292209,0.000247,8.811098e-04
41,42,Kisumu,17,2019,1155574,2085,554.2,6.317526,1.76,0.000175,0.000175,0.459578,0.099325,0.000000,0.156123,0.274464,0.000136,1.772084e-04
42,43,Homa Bay,7,2019,1131950,3153,359.0,5.883322,1.61,0.193068,0.193068,0.000266,0.464935,0.000000,0.311640,0.022954,0.003221,3.557048e-03
43,44,Migori,27,2019,1116436,2614,427.1,6.057018,1.97,0.000778,0.000778,0.522654,0.202984,0.000000,0.068827,0.182571,0.001637,3.548768e-03
44,45,Kisii,16,2019,1266860,1323,957.6,6.864430,0.95,0.000071,0.000071,0.031982,0.026365,0.000000,0.238503,0.689780,0.000038,0.000000e+00
45,46,Nyamira,34,2019,605576,897,675.1,6.514861,0.12,0.002139,0.002139,0.000016,0.280230,0.000000,0.716530,0.000974,0.000003,1.776397e-07
46,47,Nairobi,30,2019,4397073,704,6245.8,8.739665,3.37,0.004217,0.004217,0.051544,0.091598,0.000000,0.681663,0.163720,0.006244,1.147788e-05